version: '3.1'

services:

  app:
    restart: on-failure
    environment:
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      CT_STATIC: ${CT_STATIC}
      EC2_REGIONS: ${EC2_REGIONS}
    build: ./cloudtables
    expose:
      - "8000"
    volumes:
      - ${CT_STATIC}:/code/static
      - $HOME/.aws:/root/.aws
    links:
      - "db:db"
    command: /usr/local/bin/gunicorn cloudtables.wsgi:application -w 2 -b :8000

  nginx:
    restart: on-failure
    environment:
      CT_STATIC: ${CT_STATIC}
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${CT_STATIC}:/usr/share/nginx/html/static
      - ./ssl:/etc/nginx/ssl
    links:
      - app:app

  db:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: cloudtables
      POSTGRES_DB: cloudtables
    expose:
      - "5432"
    volumes:
      - ${PGDATA}:/var/lib/postgresql/data
